#!/usr/bin/env python3
from pexpect import pxssh
from getpass import getpass
import sys
from lib import hpshell
from lib import cli
import time

def checkArgument():
	if len(sys.argv) != 2:
		print("http - Connect a switch through HTTP protocal")
		print("Usage: http [user@]host")
		print("(If not specified, username is admin.)")
		sys.exit(0)
if __name__ == "__main__":
	checkArgument()
	user = input("Username:")
	print ("connecting ",sys.argv[1],"......")
	ssh = pxssh.pxssh()
	for count in range(1,3):
		password = getpass('password :')
		if password:
			try:
				ssh.login(sys.argv[1],user,password,auto_prompt_reset=False)
				break
			except:
				print ("incorrect password")
		if count==3:
			print ("can't connect to ",sys.argv[1],", or incorrect password")
			sys.exit(0)
	
	ssh.sendline("terminal length 0")
	SwitchName = cli.getSwitchName(ssh)
	hpshell.run(ssh,password,SwitchName)
