#!/usr/bin/env python3
import telnetlib
from getpass import getpass
import sys
from lib import hpshell
import time

def checkArgument():
	if len(sys.argv) != 2:
		print("http - Connect a switch through HTTP protocal")
		print("Usage: http [user@]host")
		print("(If not specified, username is admin.)")
		sys.exit(0)
if __name__ == "__main__":
	checkArgument()
	print ("connecting ",sys.argv[1],"......")
	try:
		tn = telnetlib.Telnet(sys.argv[1],timeout=10)
	except:
		print ("can't connect to ",sys.argv[1])
		sys.exit(0)
	
	user = input("Username:")
	tn.read_until(b'Password: ')
	SwitchName = ''
	while True:
		password = getpass('password :')
		if password:
			tn.write(password.encode('ascii') + b'\n')
			time.sleep(0.5)
			test_pass = tn.read_very_eager().decode('ascii')
			if test_pass.find("Password") == -1:
				temp_list = test_pass.split('\n')
				SwitchName = temp_list[1][:len(temp_list[1])-1]
				break;
			print ("incorrect  password, please try again")
	tn.write("terminal length 0".encode('ascii')+b'\n')
	print (tn.read_very_eager().decode('ascii'))
	hpshell.run(tn,password,SwitchName)
